### ISSUE TITLE
requirements.txt dosyasının oluşturulması

### ISSUE THREAD

**Issue by OmerFI** [myygunduz/pyqtCuwi#3]
Merhaba. **Python** projelerinde `requirements.txt` dosyasının oluşturulması yaygın bir ortak kullanım şeklidir. Projenizin **setup.py** dosyasındaki şu kısmı
```py
install_requires=["PyQt5>=5.15.4","pyqt5-plugins>=5.15.4.2.2","PyQt5-Qt5>=5.15.2","PyQt5-sip>=12.9.0","pyqt5-tools>=5.15.4.3.2","pyqt5Custom>=1.0.1"]
```
teker teker ayırıp bir requirements.txt dosyasına eklemenizin daha iyi olacağını düşünüyorum.
Ek olarak bilginiz varsa bir virtual environment oluşturup onun içine gerekli kütüphaneleri yükleyip aşağıdaki komutla da requirements.txt dosyasını oluşturabilirsiniz:
```
pip freeze > requirements.txt
```

**Comment by myygunduz** [comment]
Merhaba ilk kez yaptığım için `requirements.txt` dosyasından pek bilgim yoktu büyük ihtimalle sadece modül isimleri ve versiyonları yazacak araştırma yapacağım bu konu ile ilgili teşekkür ederim.  `virtual environment` kavramını da müsait bir zamanda araştıracağım üniversite sınavları yaklaştığı için ona çalışıyorum. Fikirlerin için teşekkürler.
